export { MedicalRecordView } from './MedicalRecordView'
export { MedicalRecordForm } from './MedicalRecordForm'
export type { MedicalRecordFormValues } from './MedicalRecordForm'
export { DocumentUploader } from './DocumentUploader'
export { ClinicalExamForm } from './ClinicalExamForm'
export { ClinicalExamPrintView } from './ClinicalExamPrintView'
