export { LoginPage } from './LoginPage'
export { DashboardPage } from './DashboardPage'
export { AppointmentsPage } from './AppointmentsPage'
export { PatientsPage } from './PatientsPage'
export { MedicalRecordsPage } from './MedicalRecordsPage'
export { ProceduresPage } from './ProceduresPage'
export { PricingPage } from './PricingPage'
export { ClinicsPage } from './ClinicsPage'
export { LocationsPage } from './LocationsPage'
export { NewLocationPage } from './NewLocationPage'
export { EditLocationPage } from './EditLocationPage'
export { AccountingPage } from './AccountingPage'
export { BudgetsPage } from './BudgetsPage'
export { InventoryPage } from './InventoryPage'
export { MarketingPage } from './MarketingPage'

